
name: Automated Xray Config Pipeline

on:
  schedule:
    - cron: '0 */6 * * *' # اجرای خودکار اسکن هر ۶ ساعت یک‌بار
  workflow_dispatch: # امکان اجرای دستی پایپ‌لاین از پنل گیت‌هاب اکشنز

jobs:
  validate-and-optimize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Initialize Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Network Core Component (Xray)
      run: |
        # دریافت مستقیم آخرین پکیج پایدار نسخه لینوکس ۶۴ بیت
        wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
        unzip Xray-linux-64.zip -d xray-core
        chmod +x xray-core/xray
        mv xray-core/xray ./xray
        # پاک‌سازی فایل‌های فشرده مبدا جهت مدیریت بهینه فضا
        rm -rf xray-core Xray-linux-64.zip

    - name: Execute Proxy Analysis Script
      run: python -u proxy_pipeline.py
